### ISSUE TITLE
הרגתי אויב אחד - מה הלאה?

### ISSUE THREAD

**Issue by erelsgl** [Flintlock-Entertainment/TrailBlazer#1]
הצלחתי להרוג את האויב הראשון, אבל לא הבנתי מה אמור לקרות אחר-כך?

**Comment by Eli-Levi** [comment]
> הצלחתי להרוג את האויב הראשון, אבל לא הבנתי מה אמור לקרות אחר-כך?

המשחק המלא לקורס עכשיו עלה לגיט, ולכן תוכל לעשות הרבה יותר מרק להרוג אויב אחד.
אתה מוזמן לנסות!

**Comment by erelsgl** [comment]
א. אחרי ארבעה כישלונות, הצלחתי להרוג את הבוס! אבל במקום להראות לי מסך של ניצחון, חזרתי למסך ההתחלה.

ב. יש בעיה בלוג של הקרב: השורות לא זזות בקצב הנכון, וצריך כל הזמן לגלגל כדי לראות מה קורה.

ג. כשעושים demoralize מוצלח, לא רואים שום שינוי ביריב. צריך להראות על היריב סימן כלשהו שהוא עם מורל נמוך.
